openapi: 3.0.0
info:
  title: Social-app
  description: Our 1st social app learn from lco-Sourav Chakraborty
  version: 1.0.1
servers:
  - url: http://localhost:4000/api/v1
    description: Our localhost version of the server
  - url: http://localhost:4000/api/v1
    description: Just a dummy url ,it doesn't work
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /instagram:
    get:
      summary: return username,followers & follows
      responses:
        '200': #status code
          description: returns an object 
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  Followers:
                    type: string
                  Follows:
                    type: string
  /facebook:
    get:
      summary: return username,followers & follows
      responses:
        '200': #status code
          description: returns an object 
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  Followers:
                    type: string
                  Follows:
                    type: string

  /linkedin:
    get:
      summary: return username,followers & follows
      responses:
        '200': #status code
          description: returns an object 
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  Followers:
                    type: string
                  Follows:
                    type: string

  /{token}/{extra}:
    get:
      summary: return whatever in parameter
      parameters:
        - name: token
          default: 5
          in: path
          schema:
            type: string
        - name: extra
          default: abc
          in: path
          schema:
            type: string
      responses:
        '200': #status code
          description: returns an object 
          content:
            application/json:
              schema:
                type: object
                properties:
                  params:
                    type: string
                  